cadena1= "Hola Nico"
cadena2= "Nicolas"
numero= 1

print(cadena1+cadena2) #SALEN LAS CADENAS UNIDAS, CON CATENACION SE LE LLAMA. SE SOLUCIONA PONIENDO ESPACIO EN LA ORACION DE LA CADENA 1 AL FINAL, O AL PRINCIPIO DE LA CADENA 2.
print(cadena2*5) #LO MULTIPLICA POR EL NUMERO DESEADO.

print (numero,"Hola usuario:", cadena2) #SE PUEDE USAR LA , O EL +, DA LO MISMO.
print (type(str(numero))) #SE PUEDE CONVERTIR EL NUMERO A STRING CON EL STR.